#!/usr/bin/env bash

# test

tmsu imply aubergine vegetable    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply aubergine price=100    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply price=100 expensive    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu imply price=100                       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr  

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
tmsu: new tag 'price'
tmsu: new value '100'
tmsu: new tag 'expensive'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine -> price=100
price=100 -> expensive
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
