#!/usr/bin/env bash

# test

tmsu imply eggplant aubergine     >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply aubergine vegetable    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply vegetable food         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply aubergine price=100    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu imply aubergine                       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr  

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'eggplant'
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
tmsu: new tag 'food'
tmsu: new tag 'price'
tmsu: new value '100'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine -> price=100
aubergine -> vegetable
 eggplant -> aubergine
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
