#!/usr/bin/env bash

# setup

tmsu config tagDirectories=no

mkdir -p /tmp/tmsu/dir
echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2
echo 3 >/tmp/tmsu/file3
echo 4 >/tmp/tmsu/file4
echo 5 >/tmp/tmsu/dir/file5
echo 6 >/tmp/tmsu/dir/file6
tmsu tag /tmp/tmsu/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file3 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/dir/file5 aubergine >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
rm /tmp/tmsu/file2
echo changed >>/tmp/tmsu/file3

# test

tmsu status /tmp/tmsu/dir             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
T /tmp/tmsu/dir/file5
U /tmp/tmsu/dir/file6
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
